# Generated by Django 4.2.10 on 2025-06-13 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanrequest',
            name='applicant_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='coapplicant_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='credit_history',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='dependents',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='education',
            field=models.CharField(blank=True, choices=[('Graduate', 'Graduate'), ('Not Graduate', 'Not Graduate')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='loan_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='loan_amount_term',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='loan_status',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='married',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='property_area',
            field=models.CharField(blank=True, choices=[('Urban', 'Urban'), ('Rural', 'Rural'), ('Semiurban', 'Semiurban')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='self_employed',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True),
        ),
    ]
