# Generated by Django 4.2.10 on 2025-06-13 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan_manager', '0002_loanrequest_applicant_income_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanrequest',
            name='amount',
        ),
    ]
